### ISSUE TITLE
No icon found warning

### ISSUE THREAD

**Issue by aleozlx** [hastinbe/i3-volume#11]
Hi, I have a small problem with the notification icon. It is not showing and I can see warning messages such as the following if run from the terminal.

```
WARNING: No icon found in path: 'audio-volume-high'
```

What I tried:
I have double checked the dunst config:
```
$ grep icon_path ~/.config/dunst/dunstrc
    icon_path = /usr/share/icons/Adwaita/16x16/status/:/usr/share/icons/Adwaita/16x16/devices/
```
And I do have these stuff on my system:
```
$ ls /usr/share/icons/Adwaita/16x16/status/audio* 
/usr/share/icons/Adwaita/16x16/status/audio-volume-high-symbolic.symbolic.png
/usr/share/icons/Adwaita/16x16/status/audio-volume-low-symbolic.symbolic.png
/usr/share/icons/Adwaita/16x16/status/audio-volume-medium-symbolic.symbolic.png
/usr/share/icons/Adwaita/16x16/status/audio-volume-muted-symbolic.symbolic.png
/usr/share/icons/Adwaita/16x16/status/audio-volume-overamplified-symbolic.symbolic.png
```

Not sure what else I might be missing and I'm not familiar with how dunst pulls icons, so I am not sure if it's even hitting those files or am I missing packages.

Thanks for your time.

**Comment by hastinbe** [comment]
Try to checkout branch `next` and see if that's working
