### ISSUE TITLE
More ".symbolic"-problems

### ISSUE THREAD

**Issue by gustaphe** [hastinbe/i3-volume#14]
I have a similar problem to https://github.com/hastinbe/i3-volume/issues/11 , but I'm using an icon font that calls the symbolic files "audio-volume-high-symbolic.svg" (so a middle case between legacy and the redundant "*-symbolic.symbolic" thing.
I'd suggest a numeric -l option, so that it would be
```
0: "audio-volume-high-symbolic.symbolic"
1: "audio-volume-high"
2: "audio-volume-high-symbolic"
```
(probably defaulting to 0 if not given and 1 if given without a number)

**Comment by hastinbe** [comment]
Thanks for the report. Try v2.0.0 which adds a -S option to specify a symbolic icon name suffix. I've made the "-symbolic" version the default, so you'll just need to pull from master to get the latest.

For others using icon themes using the "-symbolic.symbolic" naming scheme, you will need to specify the suffix with `-S '.symbolic'`. This is a breaking change from versions prior to v2.0.0

**Comment by gustaphe** [comment]
Nice, an update in less than a day, and a major update at that. I'm honored.
Worked like a charm.
