### ISSUE TITLE
support decimals for volume steps

### ISSUE THREAD

**Issue by n1trux** [hastinbe/i3-volume#24]
if you run `.scripts/volume up 1.5 -x 105.5`, you get `./volume: line 1025: 105.5: syntax error: invalid arithmetic operator (error token is ".5")`. It would be nice if one could use decimal values.

**Comment by hastinbe** [comment]
The main reason for this is that neither PulseAudio or alsa-utils support decimal percentage values. In PulseAudio decimals with a percentage sign get treated as dB volume (+1.5% == +1.5dB), and in `amixer` it gets rounded to the nearest integer.

I know you want support for dB volume, but for percentage volume which i3-volume is using at the moment this is not currently possible.
