### ISSUE TITLE
support raising volume to clamping/max volume even though it's not a multiple of the volume step

### ISSUE THREAD

**Issue by n1trux** [hastinbe/i3-volume#26]
If you set your vol to 0 and then execute `./volume up 3 -x 100`, you can only get to 99% because 100 is not a multiple of 3.

If you have the volume set to 98%, i3-volume won't increase the volume to the max volume set with `-x 100`.

However, if you set the volume to -0.17dBa (see also: #25) and `./volume up 1 -x 100`, it'll set the volume to 0.09dBa, which is slightly more than 100%.

Please consider changing the behaviour of the script so it a) adheres to the max volume if you have "crude" dBa volumes set, and b) increases the volume to the max volume even if it's not a multiple of the increase.

**Comment by hastinbe** [comment]
> However, if you set the volume to -0.17dBa (see also: #25) and `./volume up 1 -x 100`, it'll set the volume to 0.09dBa, which is slightly more than 100%.

Unfortunately nothing I can do about this one at the moment since we don't support dB volume, as far as the script is concerned a volume of -0.17db is 99%, so raising the volume 1% is considered OK as PA does not report percentages in decimals

**Comment by n1trux** [comment]
Thank you a lot for your fix!

Maybe you could leave the other Issues open so people see what they can work on? I don't want to tell you what to do with your repository, but it seems a little odd to me that you close "valid" issues you already thought about. Worst case someone has the same issue and opens it again, you close it again, rinse and repeat…

**Comment by hastinbe** [comment]
Don't worry, the dB issue was only converted to a discussion in [Ideas here](https://github.com/hastinbe/i3-volume/discussions/25).
