### ISSUE TITLE
sudden blue progress bar appears on dunstify notification below the original one

### ISSUE THREAD

**Issue by Zyanite7** [hastinbe/i3-volume#31]
shortcut to change volume via sxhkd:
`super + {F10, F11}
    i3-volume {down, up} 5 -np -N dunstify
`
`
super + F12
    i3-volume mute -np -N dunstify
`
what is looks like now:
![2021-05-05_3840x2160-crop](https://user-images.githubusercontent.com/43778097/117163763-4489aa00-adc4-11eb-8ab4-1d8ba35c6a1c.png)

using the -y option won't fix it, instead making the whole thing greenish like this:
![2021-05-05_3840x2160-crop](https://user-images.githubusercontent.com/43778097/117164009-80247400-adc4-11eb-9aff-6456db92e839.png)

without the -p option it still persists. 

What could be the cause of that blue progress bar appearing suddenly?

on arch with i3wm, was normal until i tried to change volume while playing a video via mpv, it was normal before.

**Comment by hastinbe** [comment]
dunst 1.6.0 added a progress bar which is displayed when a specific hint is given, which i3-volume provides. You have 2 options:

- Use dunst's progress bar and disable i3-volume's by omitting the `-p` option (recommended)
- Use i3-volume's progress bar and disable dunst's by setting `progress_bar = false` in your `dunstrc`

The drawback to disabling dunst's progress bar is that it will affect other notifications where a progress bar might be desirable such as for brightness notifications. The `-p` option in i3-volume is intended to be used when the notification daemon does not provide its own. I recommend using the notification daemon's built-in progress bar when possible. Although I understand some might prefer the styling of i3-volume's. **As a result of this, I've pushed a change where if you provide the `-p` option, i3-volume will no longer provide the hint to the notification daemon that is causing them to draw their progress bar.** Pull from master if you want that!

If styling of dunst's progress bar is a concern you can customize it in your `dunstrc`. Here are the progress bar settings for dunst:

```
    # Turn on the progess bar
    progress_bar = true

    # Set the progress bar height. This includes the frame, so make sure
    # it's at least twice as big as the frame width.
    progress_bar_height = 10

    # Set the frame width of the progress bar
    progress_bar_frame_width = 1

    # Set the minimum width for the progress bar
    progress_bar_min_width = 150

    # Set the maximum width for the progress bar
    progress_bar_max_width = 300
```

**Comment by Zyanite7** [comment]
Of course I'd like to keep the i3-volume bar, which looks much nicer than the blui one dunst provides. So I didn't change any config and pulled the newest version. It's working just fine now as before. Amazing and thank you!
