### ISSUE TITLE
Documentation outdated for i3blocks

### ISSUE THREAD

**Issue by AlfHou** [hastinbe/i3-volume#32]
Unfortunatlely there is no way to open pull requests for wiki pages, or I would have done that.

The documentation for using i3-volume with i3blocks is this
```
[i3volume]
label=
command=~/i3-volume/volume -o i3blocks
interval=once
signal=10
color=#b8bb26
separator_block_width=10
markup=pango
```
The `-o` flag doesn't work, so the example should be updated to 
```
[i3volume]
label=
command=~/i3-volume/volume output i3blocks
interval=once
signal=10
color=#b8bb26
separator_block_width=10
markup=pango
```
😃

**Comment by hastinbe** [comment]
If you want you can fork the wiki repo and push your changes, then link to it here and I can pull it

**Comment by AlfHou** [comment]
I don't think there is a way to fork wiki repos.[0] If you know how, feel free to point me to some instructions.
[0]: https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by hastinbe** [comment]
When you fork this repo the wiki comes with it, you can then go to your copy of the wiki and make the changes. Then I will pull your wiki into main once you let me know the changes have been made

**Comment by AlfHou** [comment]
![image](https://user-images.githubusercontent.com/20001253/120297941-e3bd9680-c2c9-11eb-8160-53cc14a421be.png)

Unfortunately not

**Comment by hastinbe** [comment]
Okay, so that doesn't work anymore. I made the wiki editable, you should be able to click the Edit button on https://github.com/hastinbe/i3-volume/wiki/Usage-with-i3blocks

**Comment by AlfHou** [comment]
Great thank! Fixed it now
