### ISSUE TITLE
How to use this package when there is no volume key on the keyboard.

### ISSUE THREAD

**Issue by hongyi-zhao** [hastinbe/i3-volume#33]
On Ubuntu 20.04.2 LTS, I'm using [i3wm](https://i3wm.org/) and installed this package according to the guidance [here](https://github.com/hastinbe/i3-volume/wiki/Installation#i3wm).

But it seems I don't have a volume key on the keyboard. How to use this package in this case?

Regards,
HY

**Comment by hastinbe** [comment]
You'd have to bind some other key or key combination to run the script. Since you're using i3wm you can set that up in its config file. Using the examples on the page you linked, you could change the volume keybindings to something like this, which would use your modifier key + comma, period, and slash to increase, decrease, or mute the volume

```
bindsym $mod+comma exec --no-startup-id $volumepath/volume -n -t $statuscmd -u $statussig up $volumestep
bindsym $mod+period exec --no-startup-id $volumepath/volume -n -t $statuscmd -u $statussig down $volumestep
bindsym $mod+slash exec --no-startup-id $volumepath/volume -n -t $statuscmd -u $statussig mute 
```

**Comment by hongyi-zhao** [comment]
Thank you very much. It does the trick. BTW, why the `slash` keysym notation can invoke forward slash by default?

**Comment by hastinbe** [comment]
The name is what's recognized by xmodmap, but I'm guessing (forward) slash comes first because it precedes the backslash historically and it was just called slash at that time as backslash didn't exist yet

**Comment by hongyi-zhao** [comment]
Some additional comments: I also tried the following settings for `i3wm`, which did exactly the same job as `i3-volume`:

```
# Use pactl to adjust volume in PulseAudio.
set $refresh_i3status killall -SIGUSR1 i3status
bindsym $mod+comma exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym $mod+period exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym $mod+slash exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym $mod+backslash exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status
```
So, I wonder why you prefer to create this project instead of using i3wm's local options.

**Comment by hastinbe** [comment]
It's true, you only need a single command to change your volume. There no need for this script if all you want is for your volume keys to work. But if you're the kind of person who wants to customize their desktop with different notification systems, status bars, audio platforms, or even access volume info from command line, this script tries to make that easier.

**Comment by hongyi-zhao** [comment]
Another question: it seems that i3-volume doesn't have Mic relevant configurations. Any more hints?

**Comment by hastinbe** [comment]
This script doesn't provide any specific features for microphones. But you could do it like this: `pactl set-source-mute <card> toggle`, replacing <card> with the index of your mic you can get with `pacmd list-sources`

**Comment by hongyi-zhao** [comment]
Got it. Thank you again.
