### ISSUE TITLE
Aur installation resets /etc/i3/config to default

### ISSUE THREAD

**Issue by theSkele** [hastinbe/i3-volume#35]
I had some trouble manually placing the scripts so I decided to use yay. I noticed my /etc/i3/config was completely reset to default...
Why is that necessary? I have to rewrite my config again, as I didnt do a backup because I didnt expect anything to overwrite it.

**Comment by theSkele** [comment]
Actually its the default configuration + bindings for i3-volume to work. Im assuming it resets the config and then adds in those lines.

**Comment by hastinbe** [comment]
Our Aur package doesn't modify your i3 configuration in any way, in fact i3 is not even a dependency of this package. The PKGBUILD copies the volume script, README.md, and 2 example configs for using it with i3 to your system. The example configurations are copied to `/usr/share/doc/i3-volume/` by default and you are to manually append the contents of one of the examples to your user's i3 config, such as [shown here](https://github.com/hastinbe/i3-volume/wiki/Installation#pulseaudio).

**Comment by theSkele** [comment]
My mistake, apologies, I have no Idea how I was brought to such a conclusion. Thank you for the quick and in depth response. Much appreciated
