### ISSUE TITLE
allow to increase volume more than 100% / ignore limit

### ISSUE THREAD

**Issue by srghma** [hastinbe/i3-volume#38]
I am using `i3-volume -a -n -c 0 up 100`

I want to set volume to maximum 153%

![2024-11-08_10-51-50](https://github.com/user-attachments/assets/b320863f-dcfa-4472-841a-1392d382ac20)

I think for amixer one needs to add --nocheck 
----
UPDATE

nocheck is ignored in `amixer set Master playback 150%`

related issue https://github.com/smasher164/pw-volume/issues/32

**Comment by hastinbe** [comment]
`amixer` directly interfaces with `ALSA`, which limits volume to the hardware’s maximum capability. For digital amplification (>100%), you’ll need a sound server like `PulseAudio` or `PipeWire`, which typically runs on top of `ALSA`. `PipeWire` can also operate with compatibility layers for applications expecting `ALSA` or `PulseAudio`; or even without `ALSA` in some cases. `PipeWire` would be the recommended solution, as it outperforms `PulseAudio`, is more robust, and is gradually replacing `PulseAudio` and thus is the better long-term choice
